### ISSUE TITLE
Update Genotypic Richness, Evenness, and Diversity Chapter

### ISSUE THREAD

**Issue by zkamvar** [grunwaldlab/Population_Genetics_in_R#11]
This needs to be done to reflect the changes. (i.e. Hexp is really Hexp)

**Comment by zkamvar** [comment]
Hi Nik,

I just pushed my modification of this chapter. Do you think you could take a look at it?

Thanks,
Zhian

**Comment by zkamvar** [comment]
@sporangia, can you also take a look at it? You originally wrote this chapter if I recall.

**Comment by grunwald** [comment]
Will do. Thanks,

**Comment by grunwald** [comment]
Made a few edits. Looks good to me. Close issue once reviewed by @sporangia.

**Comment by zkamvar** [comment]
Any word on this, @sporangia?

**Comment by sporangia** [comment]
Reviewed -- looks okay in this chapter.  Please proceed.

**Comment by zkamvar** [comment]
Merged.
