### ISSUE TITLE
ggplot2 3.0.0

### ISSUE THREAD

**Issue by knausb** [grunwaldlab/Population_Genetics_in_R#33]
On 2018-07-03 ggplot2 3.0.0 was released. Because this is a major release there may be changes that are not backward compatible. For our workshop we've asked participants to use the most updated version of all packages. This mean our site needs to work with ggplot2 3.0.0.

I thought it would be good to document some of this testing here. The computer we plan to present on is my Mac. We're on 10.13.5 "High Sierra". We're also at R 3.5.0 and now ggplot2 3.0.0.

**Comment by knausb** [comment]
Well, that was a bit anticlimactic. As far as I can tell we are unaffected by this upgrade. So I went ahead and ran `upgrade.packages(ask=FALSE)` as well and I think we're fine.

**Comment by knausb** [comment]
And we appear to build fine on Ubuntu 16.0.4 LTS with R 3.4.4 and ggplot2 3.0.0.

**Comment by Neato-Nick** [comment]
And on my Windows 10 machine as well, running R 3.5.1
