### ISSUE TITLE
how to get a newick format tree output file

### ISSUE THREAD

**Issue by liuyongming0612** [grunwaldlab/Population_Genetics_in_R#40]
dear guys:
 use aboot function, we will get a tree result. But I want to plot it with another tree plot software, can anybody tell me how to get a newick format tree output file from aboot function's result.

very appreciate

**Comment by zkamvar** [comment]
Hi,

Ape has the write.tree() function, which will write the tree in NEWICK
format:
https://www.rdocumentation.org/packages/ape/versions/5.3/topics/write.tree

**Comment by Neato-Nick** [comment]
Yes, use write.tree

An example based on [Ape Documentation](https://www.rdocumentation.org/packages/ape/versions/5.4-1/topics/write.tree)

``` r
library(ape)
owls_newick <- "owls(((Strix_aluco:4.2,Asio_otus:4.2):3.1,Athene_noctua:7.3):6.3,Tyto_alba:13.5);"
owls_phylo <- read.tree(text=owls_newick)
plot(owls_phylo)
```

![](https://i.imgur.com/1MAtAwb.png)

``` r
write.tree(owls_phylo)
#> [1] "(((Strix_aluco:4.2,Asio_otus:4.2):3.1,Athene_noctua:7.3):6.3,Tyto_alba:13.5);"
```

<sup>Created on 2021-02-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
