### ISSUE TITLE
Test of Hardy–Weinberg Equilibrium for X-chromosomal markers

### ISSUE THREAD

**Issue by cloudred20** [grunwaldlab/Population_Genetics_in_R#42]
Hi,

Can the "hw.test" function of "pegas" package be used for testing HWE for X-chromosomal markers, similar to "HWChisq" of "HardyWeinberg" package? If yes, then how to input the data for males?

**Comment by knausb** [comment]
Hi @megha20 , you appear to have cross posted this at https://github.com/emmanuelparadis/pegas/issues/47#issue-625244612. Because this is a question about a `pegas` function I feel it is more appropriate there.
